// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bftoxhyduevhtdwkpzba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmdG94aHlkdWV2aHRkd2twemJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjY4OTEsImV4cCI6MjA2NTM0Mjg5MX0.YK7VjyBQIi6O7edczZvHNpG5CXo0jwBSm2F-H8_sU0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);